# Travis CI configuration
language: python
sudo: required
python:
    - '3.6'
    - '3.7'
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - numpy
  - pandas
  - os
  - seaborn
  - matplotlib
  - math
  - warnings

script: pytest